# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "niromanoS" do |control|
    control.vm.hostname = "niromanoS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provision "shell", path: "scripts/server.sh"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  config.vm.define "niromanoSW" do |control|
    control.vm.hostname = "niromanoSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provision "shell", path: "scripts/serverWorker.sh"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
  end
end
